name: Build, Push & Deploy to SKS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/site-cyna:latest

      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Install or upgrade ingress-nginx with Helm
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx --create-namespace \
            --set controller.service.type=LoadBalancer \
            --set controller.admissionWebhooks.enabled=true \
            --set controller.admissionWebhooks.patch.enabled=true \
            --set controller.admissionWebhooks.failurePolicy=Ignore

      - name: Clean up potential leftover resources
        continue-on-error: true
        run: |
          kubectl delete ingress site-cyna-ingress || true
          kubectl delete svc site-cyna-service || true

      - name: Deploy to Kubernetes
        run: |
          kubectl apply --validate=false -f k8s/site-cyna.yaml
          kubectl apply --validate=false -f k8s/site-cyna-ingress.yaml
